REPORT_TEXT = {
    "zh": {
        "classification": "政务归档 · 算法公平性审计",
        "report_no": "报告编号",
        "issued_at": "签发时间",
        "authority": "签发机构",
        "algorithm": "待测算法",
        "dataset": "测试图集",
        "summary": "审计结论摘要",
        "passed": "符合设定公平阈值",
        "failed": "未达到设定公平阈值",
        "overall_accuracy": "总体准确率",
        "max_gap": "最大群体差值",
        "bias_coefficient": "公平偏差系数",
        "std_deviation": "标准差",
        "group_results": "分组评测结果",
        "group": "人口群体",
        "samples": "样本量",
        "accuracy": "识别准确率",
        "gap": "相对差值",
        "status": "合规状态",
        "compliant": "合规",
        "warning": "告警",
        "methodology": "评测方法与口径",
        "methodology_body": (
            "本报告按人工修正优先原则确定人口属性分组，逐样本调用待测接口，"
            "以各群体准确率、最大群体差值、公平偏差系数及标准差进行综合审计。"
        ),
        "failed_samples": "失败样本汇总",
        "failed_note": "接口失败样本不计入准确率分母，已单独归档并保留重试记录。",
        "failed_sample_id": "样本编号",
        "failure_code": "错误代码",
        "failure_reason": "失败原因",
        "retries": "重试次数",
        "no_failed_samples": "本次评测未发现失败样本。",
        "signer": "审核签发人",
        "checksum": "文件校验摘要",
        "footer": "Fair Bench｜公允准鉴 · 公共AI监管评测平台",
        "demo_dataset": "公共场景人脸公平性基准集 2026-Q2",
    },
    "en": {
        "classification": "Government Archive · Algorithm Fairness Audit",
        "report_no": "Report No.",
        "issued_at": "Issued at",
        "authority": "Issuing authority",
        "algorithm": "Algorithm under test",
        "dataset": "Test dataset",
        "summary": "Executive audit conclusion",
        "passed": "Within the configured fairness threshold",
        "failed": "Outside the configured fairness threshold",
        "overall_accuracy": "Overall accuracy",
        "max_gap": "Maximum group gap",
        "bias_coefficient": "Fairness bias coefficient",
        "std_deviation": "Standard deviation",
        "group_results": "Group evaluation results",
        "group": "Demographic group",
        "samples": "Samples",
        "accuracy": "Recognition accuracy",
        "gap": "Relative gap",
        "status": "Compliance",
        "compliant": "Compliant",
        "warning": "Alert",
        "methodology": "Methodology and measurement basis",
        "methodology_body": (
            "Demographic grouping prioritizes manual corrections. Each sample is sent "
            "to the target API and assessed using group accuracy, maximum group gap, "
            "fairness bias coefficient, and standard deviation."
        ),
        "failed_samples": "Failed sample summary",
        "failed_note": (
            "API failures are excluded from the accuracy denominator and archived "
            "separately with retry history."
        ),
        "failed_sample_id": "Sample ID",
        "failure_code": "Error code",
        "failure_reason": "Failure reason",
        "retries": "Retries",
        "no_failed_samples": "No failed samples were recorded for this evaluation.",
        "signer": "Authorized reviewer",
        "checksum": "File checksum",
        "footer": "Fair Bench · Public AI Regulatory Evaluation Platform",
        "demo_dataset": "Public-Space Facial Fairness Benchmark 2026-Q2",
    },
}
